const state={songs:[],selectedId:"",filter:"",authenticated:false,producer:{jobs:[],packages:[]},producerTimer:null};
const $=selector=>document.querySelector(selector);
const elements={shell:$("#catalogShell"),songList:$("#songList"),empty:$("#emptyState"),workspace:$("#songWorkspace"),search:$("#searchInput"),status:$("#statusMessage"),songDialog:$("#songDialog"),versionDialog:$("#versionDialog")};
const uploadHelper=window.HaloUploadProgress;
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const titleCase=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const money=cents=>cents==null?"Not priced":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const AUDIO_CHUNK_BYTES=4*1024*1024;
const MAX_AUDIO_BYTES=128*1024*1024;
const ARTWORK_CHUNK_BYTES=4*1024*1024;
const MAX_ARTWORK_BYTES=20*1024*1024;
const uploadUi={audio:uploadHelper.createUploadUi({panel:document.querySelector(".audio-upload-panel"),status:$("#audioUploadProgress"),track:$("#audioUploadTrack"),fill:$("#audioUploadTrack .upload-progress-fill"),idleMessage:"No uploaded file yet."}),artwork:uploadHelper.createUploadUi({panel:document.querySelector(".artwork-upload-panel"),status:$("#artworkUploadProgress"),track:$("#artworkUploadTrack"),fill:$("#artworkUploadTrack .upload-progress-fill"),idleMessage:"No artwork uploaded yet."}),versionArtwork:uploadHelper.createUploadUi({panel:document.querySelector(".version-artwork-panel"),status:$("#versionArtworkProgress"),track:$("#versionArtworkTrack"),fill:$("#versionArtworkTrack .upload-progress-fill"),idleMessage:"No version artwork uploaded. Uses the song cover by default."})};

function message(text){elements.status.textContent=text;elements.status.classList.add("is-visible");clearTimeout(message.timer);message.timer=setTimeout(()=>elements.status.classList.remove("is-visible"),3200)}
async function api(payload){const options=payload?{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(payload)}:{credentials:"same-origin",headers:{Accept:"application/json"}};const response=await fetch("/api/song-catalog",options);const data=await response.json().catch(()=>({message:"Catalog response could not be read"}));if(!response.ok)throw new Error(data.message||"Catalog request failed");return data}
async function audioApi(options){const response=await fetch("/api/song-catalog/audio",{credentials:"same-origin",...options});const data=await response.json().catch(()=>({message:"Audio response could not be read"}));if(!response.ok)throw new Error(data.message||"Audio upload failed");return data}
async function artworkApi(options){const response=await fetch("/api/song-catalog/artwork",{credentials:"same-origin",...options});const data=await response.json().catch(()=>({message:"Artwork response could not be read"}));if(!response.ok)throw new Error(data.message||"Artwork request failed");return data}
function audioContentType(file){const aliases={"audio/mp3":"audio/mpeg","audio/x-mp3":"audio/mpeg","audio/m4a":"audio/mp4","audio/x-m4a":"audio/mp4","video/mp4":"audio/mp4","audio/x-aac":"audio/aac","application/ogg":"audio/ogg","audio/wave":"audio/wav","audio/vnd.wave":"audio/wav","audio/x-flac":"audio/flac","application/x-flac":"audio/flac"};if(aliases[file.type])return aliases[file.type];if(file.type?.startsWith("audio/"))return file.type;const extension=file.name.split(".").pop()?.toLowerCase();return{mp3:"audio/mpeg",m4a:"audio/mp4",mp4:"audio/mp4",aac:"audio/aac",ogg:"audio/ogg",webm:"audio/webm",wav:"audio/wav",flac:"audio/flac"}[extension]||""}
function audioDuration(file){return new Promise(resolve=>{const audio=document.createElement("audio");const url=URL.createObjectURL(file);const finish=value=>{URL.revokeObjectURL(url);resolve(Number.isFinite(value)?Math.round(value):0)};audio.preload="metadata";audio.addEventListener("loadedmetadata",()=>finish(audio.duration),{once:true});audio.addEventListener("error",()=>finish(0),{once:true});audio.src=url})}
const uploadReadyLabel=file=>`${file.name} · ${Math.max(1,Math.round(file.size/1024/1024))} MB ready to upload`;
async function uploadVersionAudio(){const file=$("#audioFile").files?.[0];const songId=$("#versionSongId").value;const versionId=$("#versionId").value;const button=$("#uploadAudioButton");if(!file){message("Choose an audio file first.");return}const contentType=audioContentType(file);if(!contentType){message("Choose an MP3, M4A, AAC, OGG, WebM, WAV, or FLAC file.");return}if(file.size>MAX_AUDIO_BYTES){message("Song audio uploads are limited to 128 MB.");return}const uploadId=crypto.randomUUID();button.disabled=true;button.textContent="Uploading…";uploadUi.audio.start(`Uploading 0% · ${file.name}`);try{const durationSeconds=await audioDuration(file);const {chunkCount}=await uploadHelper.uploadChunkedFile({url:"/api/song-catalog/audio",file,chunkSize:AUDIO_CHUNK_BYTES,buildBody({chunkIndex,chunkCount,start,end}){const form=new FormData();form.append("songId",songId);form.append("versionId",versionId);form.append("uploadId",uploadId);form.append("chunkIndex",String(chunkIndex));form.append("chunkCount",String(chunkCount));form.append("byteSize",String(file.size));form.append("filename",file.name);form.append("contentType",contentType);form.append("chunk",file.slice(start,end,contentType),file.name);return form;},onProgress(percent){uploadUi.audio.progress(percent,`Uploading ${Math.round(percent)}% · ${file.name}`);}});uploadUi.audio.progress(100,"Finishing upload and running Dream Weaver…");const data=await audioApi({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"finalize_upload",songId,versionId,uploadId,chunkCount,byteSize:file.size,filename:file.name,contentType,durationSeconds})});uploadUi.audio.success("Audio uploaded and saved.",true);message(data.message);await loadCatalog(songId);openVersion(versionId,songId)}catch(error){uploadUi.audio.fail(error.message);message(error.message)}finally{button.disabled=false;button.textContent="Upload selected audio"}}

function artworkContentType(file){if(["image/jpeg","image/png","image/webp"].includes(file.type))return file.type;const ext=file.name.split(".").pop()?.toLowerCase();return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp"}[ext]||""}
async function uploadArtwork(){const file=$("#artworkFile").files?.[0];const song=selectedSong();if(!song){message("Select a song first.");return}if(!file){message("Choose an image file first.");return}const contentType=artworkContentType(file);if(!contentType){message("Choose a JPEG, PNG, or WebP image file.");return}if(file.size>MAX_ARTWORK_BYTES){message("Artwork uploads are limited to 20 MB.");return}const songId=song.id;const uploadId=crypto.randomUUID();const button=$("#uploadArtworkButton");button.disabled=true;button.textContent="Uploading…";uploadUi.artwork.start(`Uploading 0% · ${file.name}`);try{const {chunkCount}=await uploadHelper.uploadChunkedFile({url:"/api/song-catalog/artwork",file,chunkSize:ARTWORK_CHUNK_BYTES,buildBody({chunkIndex,chunkCount,start,end}){const form=new FormData();form.append("songId",songId);form.append("uploadId",uploadId);form.append("chunkIndex",String(chunkIndex));form.append("chunkCount",String(chunkCount));form.append("byteSize",String(file.size));form.append("filename",file.name);form.append("contentType",contentType);form.append("chunk",file.slice(start,end,contentType),file.name);return form;},onProgress(percent){uploadUi.artwork.progress(percent,`Uploading ${Math.round(percent)}% · ${file.name}`);}});uploadUi.artwork.progress(100,"Finishing artwork upload…");const data=await artworkApi({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"finalize_upload",songId,uploadId,chunkCount,byteSize:file.size,filename:file.name,contentType})});uploadUi.artwork.success("Artwork uploaded and saved.",true);message(data.message);await loadCatalog(songId)}catch(error){uploadUi.artwork.fail(error.message);message(error.message)}finally{button.disabled=false;button.textContent="Upload artwork"}}
async function deleteArtwork(){const song=selectedSong();if(!song)return;try{const data=await artworkApi({method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({songId:song.id})});message(data.message);await loadCatalog(song.id)}catch(error){message(error.message)}}
async function uploadVersionArtwork(){const file=$("#versionArtworkFile").files?.[0];const songId=$("#versionSongId").value;const versionId=$("#versionId").value;if(!file){message("Choose an image file first.");return}const contentType=artworkContentType(file);if(!contentType){message("Choose a JPEG, PNG, or WebP image file.");return}if(file.size>MAX_ARTWORK_BYTES){message("Artwork uploads are limited to 20 MB.");return}const uploadId=crypto.randomUUID();const button=$("#uploadVersionArtworkButton");button.disabled=true;button.textContent="Uploading…";uploadUi.versionArtwork.start(`Uploading 0% · ${file.name}`);try{const {chunkCount}=await uploadHelper.uploadChunkedFile({url:"/api/song-catalog/artwork",file,chunkSize:ARTWORK_CHUNK_BYTES,buildBody({chunkIndex,chunkCount,start,end}){const form=new FormData();form.append("songId",songId);form.append("versionId",versionId);form.append("uploadId",uploadId);form.append("chunkIndex",String(chunkIndex));form.append("chunkCount",String(chunkCount));form.append("byteSize",String(file.size));form.append("filename",file.name);form.append("contentType",contentType);form.append("chunk",file.slice(start,end,contentType),file.name);return form;},onProgress(percent){uploadUi.versionArtwork.progress(percent,`Uploading ${Math.round(percent)}% · ${file.name}`);}});uploadUi.versionArtwork.progress(100,"Finishing artwork upload…");const data=await artworkApi({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"finalize_upload",songId,versionId,uploadId,chunkCount,byteSize:file.size,filename:file.name,contentType})});uploadUi.versionArtwork.success("Version artwork uploaded and saved.",true);message(data.message);await loadCatalog(songId);openVersion(versionId,songId)}catch(error){uploadUi.versionArtwork.fail(error.message);message(error.message)}finally{button.disabled=false;button.textContent="Upload version artwork"}}
async function deleteVersionArtwork(){const songId=$("#versionSongId").value;const versionId=$("#versionId").value;if(!songId||!versionId)return;try{const data=await artworkApi({method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({songId,versionId})});message(data.message);await loadCatalog(songId);openVersion(versionId,songId)}catch(error){message(error.message)}}
async function deleteVersionAudio(){const songId=$("#versionSongId").value;const versionId=$("#versionId").value;if(!songId||!versionId)return;try{const data=await audioApi({method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({songId,versionId})});message(data.message);await loadCatalog(songId);openVersion(versionId,songId)}catch(error){message(error.message)}}
function renderVersionAudio(version){const preview=$("#audioPreview");const deleteBtn=$("#deleteVersionAudioButton");const stateLabel=$("#audioStateLabel");if(deleteBtn)deleteBtn.hidden=!version?.audioUrl;preview.hidden=!version?.audioUrl;preview.src=version?.audioUrl||"";if(stateLabel){if(preview._onAudioError)preview.removeEventListener("error",preview._onAudioError);if(preview._onAudioLoadStart)preview.removeEventListener("loadstart",preview._onAudioLoadStart);if(preview._onAudioCanPlay)preview.removeEventListener("canplay",preview._onAudioCanPlay);if(version?.audioUrl){stateLabel.hidden=false;stateLabel.dataset.state="loading";stateLabel.textContent="Loading audio…";preview._onAudioError=()=>{stateLabel.dataset.state="error";stateLabel.textContent="Playback failed — try re-uploading the file";stateLabel.hidden=false};preview._onAudioLoadStart=()=>{stateLabel.dataset.state="loading";stateLabel.textContent="Loading audio…";stateLabel.hidden=false};preview._onAudioCanPlay=()=>{stateLabel.dataset.state="ready";stateLabel.textContent="Ready to play";stateLabel.hidden=false};preview.addEventListener("error",preview._onAudioError);preview.addEventListener("loadstart",preview._onAudioLoadStart);preview.addEventListener("canplay",preview._onAudioCanPlay)}else{stateLabel.hidden=true;stateLabel.dataset.state="";stateLabel.textContent=""}}uploadUi.audio.idle(version?.audioFilename?`${version.audioFilename} · ${Math.max(1,Math.round(version.audioByteSize/1024/1024))} MB stored`:"No uploaded file yet.")}
function renderVersionArtwork(version){const preview=$("#versionArtworkPreview");const placeholder=$("#versionArtworkPlaceholder");const deleteBtn=$("#deleteVersionArtworkButton");if(version?.artworkUrl){preview.src=version.artworkUrl;preview.alt="Version artwork";preview.hidden=false;placeholder.hidden=true;if(deleteBtn)deleteBtn.hidden=false;uploadUi.versionArtwork.idle(`Artwork uploaded${version.artworkUploadedAt?" · "+new Date(version.artworkUploadedAt).toLocaleDateString():""}.`)}else{preview.src="";preview.hidden=true;placeholder.hidden=false;if(deleteBtn)deleteBtn.hidden=true;uploadUi.versionArtwork.idle("No version artwork uploaded. Uses the song cover by default.")}}
function renderArtwork(song){const preview=$("#artworkPreview");const placeholder=$("#artworkPlaceholder");const deleteBtn=$("#deleteArtworkButton");const headingArt=$("#songHeadingArtwork");if(song?.artworkUrl){preview.src=song.artworkUrl;preview.alt=`${song.title} album artwork`;preview.hidden=false;placeholder.hidden=true;if(deleteBtn)deleteBtn.hidden=false;if(headingArt){headingArt.src=song.artworkUrl;headingArt.alt=`${song.title} artwork`;headingArt.hidden=false}uploadUi.artwork.idle(`Artwork uploaded${song.artworkUploadedAt?" · "+new Date(song.artworkUploadedAt).toLocaleDateString():""}.`)}else{preview.src="";preview.hidden=true;placeholder.hidden=false;if(deleteBtn)deleteBtn.hidden=true;if(headingArt)headingArt.hidden=true;uploadUi.artwork.idle("No artwork uploaded yet.")}}

async function loadCatalog(preferredId=""){elements.shell.setAttribute("aria-busy","true");try{const data=await api();state.authenticated=Boolean(data.authenticated);if(!data.authenticated){state.songs=[];state.producer={jobs:[],packages:[]};render();message("Sign in to load and manage your song catalog.");return}state.songs=data.songs||[];state.producer=data.producer||{jobs:[],packages:[]};state.selectedId=preferredId||state.selectedId||state.songs[0]?.id||"";if(!state.songs.some(song=>song.id===state.selectedId))state.selectedId=state.songs[0]?.id||"";render()}catch(error){message(error.message)}finally{elements.shell.setAttribute("aria-busy","false")}}
function selectedSong(){return state.songs.find(song=>song.id===state.selectedId)}

function renderSummary(){const radioQueue=state.songs.flatMap(song=>song.versions.filter(version=>["radio_edit","clean"].includes(version.versionType)&&version.masteringStatus!=="approved"));const ready=state.songs.filter(song=>song.metadataStatus==="ready");const priced=state.songs.filter(song=>song.saleStatus==="for_sale"&&song.salePriceCents>0);const average=state.songs.length?Math.round(state.songs.reduce((sum,song)=>sum+song.metadataScore,0)/state.songs.length):0;$("#songCount").textContent=state.songs.length;$("#saleCount").textContent=priced.length;$("#radioCount").textContent=radioQueue.length;$("#readyCount").textContent=ready.length;$("#overallScore").textContent=state.songs.length?average:"—";$("#overallCopy").textContent=state.songs.length?`${ready.length} of ${state.songs.length} songs fully cleared.`:"Load songs to begin the review."}
function renderSongList(){const query=state.filter.trim().toLowerCase();const songs=state.songs.filter(song=>`${song.artistName} ${song.title}`.toLowerCase().includes(query));elements.songList.innerHTML=songs.length?songs.map(song=>`<button class="song-card${song.id===state.selectedId?" is-active":""}" type="button" data-song-id="${song.id}">${song.artworkUrl?`<img class="song-card-artwork" src="${escapeHtml(song.artworkUrl)}" alt="" aria-hidden="true">`:"<span class=\"song-card-artwork-placeholder\" aria-hidden=\"true\"></span>"}<span><strong>${escapeHtml(song.title)}</strong><small>${escapeHtml(song.artistName)}</small><em>${escapeHtml(money(song.salePriceCents))}</em></span><i class="${song.metadataStatus==="ready"?"is-ready":""}" aria-label="${escapeHtml(titleCase(song.metadataStatus))}"></i></button>`).join(""):`<div class="song-card"><span><strong>No songs found</strong><small>Try another search</small></span></div>`}
function setValue(id,value){const element=$(id);if(element)element.value=value??""}
function renderWorkspace(){const song=selectedSong();elements.empty.hidden=Boolean(song);elements.workspace.hidden=!song;if(!song)return;$("#songArtist").textContent=song.artistName;$("#songTitle").textContent=song.title;$("#songRouteSummary").textContent=`${song.versions.length} versions routed · ${money(song.salePriceCents)}`;$("#songScore").textContent=song.metadataScore;$("#songStatus").textContent=titleCase(song.metadataStatus);const _pipelineEl=$("#songPipelineStage");if(_pipelineEl)_pipelineEl.textContent=(song.pipelineStage||"uploaded").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());setValue("#songId",song.id);setValue("#artistName",song.artistName);setValue("#title",song.title);setValue("#albumTitle",song.albumTitle);setValue("#genre",song.genre);setValue("#isrc",song.isrc);setValue("#upc",song.upc);setValue("#rightsStatus",song.rightsStatus);setValue("#saleStatus",song.saleStatus);setValue("#salePrice",song.salePriceCents==null?"":(song.salePriceCents/100).toFixed(2));$("#explicitLyrics").checked=song.explicitLyrics;setValue("#songNotes",song.notes);renderIssues(song);renderVersions(song);renderArtwork(song)}
function renderIssues(song){const issues=Array.isArray(song.metadataIssues)?song.metadataIssues:[];$("#reviewIntro").textContent=song.reviewedAt?`Last checked ${new Date(song.reviewedAt).toLocaleString()}. Dream Weaver checks again after every save.`:"Dream Weaver checks the information and version routing after every save.";$("#issueList").innerHTML=issues.length?issues.map(issue=>`<article class="review-issue${issue.level==="warning"?" is-warning":""}"><i></i><div><strong>${escapeHtml(issue.level)} · ${escapeHtml(titleCase(issue.field))}</strong><p>${escapeHtml(issue.message)}</p></div></article>`).join(""):`<div class="review-clear">All catalog and routing checks passed.</div>`}
function renderVersions(song){const order=["sale_master","radio_edit","clean","instrumental","stems","extended","demo","alternate"];const versions=[...song.versions].sort((a,b)=>order.indexOf(a.versionType)-order.indexOf(b.versionType));const songArt=song.artworkUrl||"";$("#versionTable").innerHTML=versions.map(version=>{const art=version.artworkUrl||songArt;const thumb=art?`<img class="version-row-artwork" src="${escapeHtml(art)}" alt="" aria-hidden="true">`:`<span class="version-row-artwork-placeholder" aria-hidden="true"></span>`;return`<button class="version-row" type="button" data-version-id="${version.id}">${thumb}<span><strong>${escapeHtml(version.label)}</strong><small>${escapeHtml(titleCase(version.versionType))}</small></span><span class="version-destination">${escapeHtml(titleCase(version.destination))}</span><span class="version-audio${version.audioUrl?" is-connected":""}">${version.audioUrl?"▶ Audio ready":"Needs audio"}</span><span class="status-pill${version.masteringStatus==="approved"?" is-approved":""}">${escapeHtml(titleCase(version.masteringStatus))}</span><b>→</b></button>`}).join("")}
function renderRadioQueue(){const queue=state.songs.flatMap(song=>song.versions.filter(version=>["radio_edit","clean"].includes(version.versionType)&&version.masteringStatus!=="approved").map(version=>({song,version})));$("#radioQueue").innerHTML=queue.length?queue.map(({song,version})=>`<article class="queue-row"><span><strong>${escapeHtml(song.title)}</strong><small>${escapeHtml(song.artistName)}</small></span><span class="queue-version">${escapeHtml(version.label)}</span><span class="queue-target">${version.targetLufs} LUFS · ${version.truePeakDbtp} dBTP</span><span>${escapeHtml(titleCase(version.masteringStatus))}</span><button class="quiet-button" type="button" data-queue-song="${song.id}" data-queue-version="${version.id}">Open</button></article>`).join(""):`<p class="queue-empty">Every radio version is approved. Nothing is waiting in the mastering queue.</p>`}
function render(){renderSummary();renderSongList();renderWorkspace();renderProducer();renderRadioQueue()}

async function requestSignIn(){try{if(!window.haloIdentity){message("The sign-in service is still loading. Try again in a moment.");return false}await window.haloIdentity.login();await loadCatalog();return state.authenticated}catch{message("Sign-in was not completed.");return false}}
async function openSongDialog(){if(!state.authenticated&&!(await requestSignIn()))return;elements.songDialog.showModal();$("#newArtistName").focus()}
function openVersion(versionId,songId=state.selectedId){const song=state.songs.find(item=>item.id===songId);const version=song?.versions.find(item=>item.id===versionId);if(!song||!version)return;state.selectedId=song.id;render();setValue("#versionId",version.id);setValue("#versionSongId",song.id);setValue("#versionType",version.versionType);setValue("#versionLabel",version.label);setValue("#masteringStatus",version.masteringStatus);setValue("#audioUrl",version.audioUrl?.startsWith("https://")?version.audioUrl:"");setValue("#durationSeconds",version.durationSeconds||"");setValue("#targetLufs",version.targetLufs);setValue("#truePeakDbtp",version.truePeakDbtp);$("#cleanLyrics").checked=version.cleanLyrics;$("#saleEnabled").checked=version.saleEnabled;setValue("#versionNotes",version.notes);$("#audioFile").value="";renderVersionAudio(version);$("#versionDestination").textContent=titleCase(version.destination);$("#versionHeading").textContent=`${song.title} · ${version.label}`;const versionArtFile=$("#versionArtworkFile");if(versionArtFile)versionArtFile.value="";renderVersionArtwork(version);if(!elements.versionDialog.open)elements.versionDialog.showModal()}
async function importExisting(){if(!state.authenticated&&!(await requestSignIn()))return;try{message("Loading existing HALO releases…");const data=await api({action:"import_existing"});message(data.message);await loadCatalog()}catch(error){message(error.message)}}

function renderProducer(){const latest=state.producer.jobs?.[0];const packages=state.producer.packages||[];const status=$("#producerStatus");const runButton=$("#runProducerButton");const active=latest&&["queued","working"].includes(latest.status);runButton.disabled=Boolean(active);runButton.textContent=active?`Working · ${latest.progress}%`:"Build album + mix ideas";status.textContent=latest?latest.status==="ready"?(latest.packageCount?`${latest.packageCount} packages ready for review`:latest.errorMessage||"No sale-ready songs found"):latest.status==="failed"?latest.errorMessage||"The last run needs attention":`${titleCase(latest.stage)} · ${latest.progress}%`:"Waiting for a catalog run";$("#producerGrid").innerHTML=packages.length?packages.map(item=>{const visibleTracks=item.tracks.slice(0,6);const remaining=item.tracks.length-visibleTracks.length;return`<article class="producer-card"><header><div><span class="package-type">${escapeHtml(item.packageType)} · ${item.trackCount} tracks</span><h3>${escapeHtml(item.title)}</h3></div><div class="package-price"><strong>${money(item.priceCents)}</strong><small>${money(item.projectedMonthlyNetCents)} net / month at 100 sales</small></div></header><p>${escapeHtml(item.description)}</p><div class="producer-tracks">${visibleTracks.map(track=>`<div class="producer-track"><span>${String(track.position).padStart(2,"0")}</span><strong>${escapeHtml(track.title)}</strong><small>${escapeHtml(track.artistName)}</small></div>`).join("")}${remaining?`<div class="producer-track"><span>+</span><strong>${remaining} more song${remaining===1?"":"s"}</strong><small>inside package</small></div>`:""}</div><p>${escapeHtml(item.rationale)}</p><footer><span>${escapeHtml(titleCase(item.status))}</span><div class="package-buttons">${item.status==="draft"?`<button class="primary-button" type="button" data-package-status="approved" data-package-id="${item.id}">Approve</button>`:""}${item.status==="approved"?`<button class="primary-button" type="button" data-package-status="published" data-package-id="${item.id}">Mark published</button>`:""}<button class="quiet-button" type="button" data-package-status="archived" data-package-id="${item.id}">Archive</button></div></footer></article>`}).join(""):`<div class="producer-empty"><strong>No packages yet.</strong><span>Run Dreamweaver after songs have cleared rights, pricing, audio, and mastering.</span></div>`;if(active&&!state.producerTimer)state.producerTimer=setTimeout(async()=>{state.producerTimer=null;await loadCatalog()},2200);if(!active&&state.producerTimer){clearTimeout(state.producerTimer);state.producerTimer=null}}
async function runProducer(){if(!state.authenticated&&!(await requestSignIn()))return;try{const data=await api({action:"queue_catalog_producer"});message(data.message);await fetch("/api/song-catalog/producer",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({jobId:data.jobId})});await loadCatalog()}catch(error){message(error.message)}}
async function setPackageStatus(packageId,status){try{const data=await api({action:"set_package_status",packageId,status});message(data.message);await loadCatalog()}catch(error){message(error.message)}}

elements.songList.addEventListener("click",event=>{const button=event.target.closest("[data-song-id]");if(!button)return;state.selectedId=button.dataset.songId;render()});
elements.search.addEventListener("input",()=>{state.filter=elements.search.value;renderSongList()});
$("#addSongButton").addEventListener("click",openSongDialog);document.querySelectorAll("[data-add-song]").forEach(button=>button.addEventListener("click",openSongDialog));
$("#importButton").addEventListener("click",importExisting);document.querySelectorAll("[data-import]").forEach(button=>button.addEventListener("click",importExisting));
document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));
document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()}));
$("#newSongForm").addEventListener("submit",async event=>{event.preventDefault();try{const data=await api({action:"create_song",artistName:$("#newArtistName").value,title:$("#newTitle").value,genre:$("#newGenre").value,salePriceCents:Math.round(Number($("#newSalePrice").value||0)*100)});elements.songDialog.close();event.currentTarget.reset();message(data.message);await loadCatalog(data.songId)}catch(error){message(error.message)}});
$("#songForm").addEventListener("submit",async event=>{event.preventDefault();try{const data=await api({action:"save_song",songId:$("#songId").value,artistName:$("#artistName").value,title:$("#title").value,albumTitle:$("#albumTitle").value,genre:$("#genre").value,isrc:$("#isrc").value,upc:$("#upc").value,rightsStatus:$("#rightsStatus").value,saleStatus:$("#saleStatus").value,salePriceCents:Math.round(Number($("#salePrice").value||0)*100),explicitLyrics:$("#explicitLyrics").checked,notes:$("#songNotes").value});message(data.message);await loadCatalog(data.songId)}catch(error){message(error.message)}});
$("#versionTable").addEventListener("click",event=>{const button=event.target.closest("[data-version-id]");if(button)openVersion(button.dataset.versionId)});
$("#radioQueue").addEventListener("click",event=>{const button=event.target.closest("[data-queue-version]");if(button)openVersion(button.dataset.queueVersion,button.dataset.queueSong)});
$("#audioFile").addEventListener("change",()=>{const file=$("#audioFile").files?.[0];uploadUi.audio.idle(file?uploadReadyLabel(file):"No file selected.")});
$("#uploadAudioButton").addEventListener("click",uploadVersionAudio);
$("#deleteVersionAudioButton").addEventListener("click",deleteVersionAudio);
async function loadRadioPickerTracks(){const list=$("#radioPickerList");list.innerHTML='<p class="radio-picker-loading">Loading your radio tracks…</p>';list.hidden=false;try{const data=await audioApi({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"list_radio_tracks"})});if(!data.tracks?.length){list.innerHTML='<p class="radio-picker-empty">No radio tracks found. Upload a track to HALO Radio first, then come back here to import it.</p>';return}list.innerHTML=data.tracks.map(track=>`<button class="radio-picker-track" type="button" data-radio-track-id="${escapeHtml(track.id)}" data-radio-track-title="${escapeHtml(track.title)}"><strong>${escapeHtml(track.title)}</strong><small>${escapeHtml(track.artist)}${track.filename?" · "+escapeHtml(track.filename):""}</small></button>`).join("")}catch(error){list.innerHTML=`<p class="radio-picker-error">${escapeHtml(error.message)}</p>`}}
async function importRadioTrack(radioTrackId,radioTrackTitle){const songId=$("#versionSongId").value;const versionId=$("#versionId").value;if(!songId||!versionId||!radioTrackId)return;$("#radioPickerList").hidden=true;uploadUi.audio.start(`Importing "${radioTrackTitle}" from Radio…`);try{const data=await audioApi({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"import_from_radio",songId,versionId,radioTrackId})});uploadUi.audio.success("Radio track imported and connected.",true);message(data.message);await loadCatalog(songId);openVersion(versionId,songId)}catch(error){uploadUi.audio.fail(error.message);message(error.message)}}
$("#importFromRadioButton").addEventListener("click",()=>{const list=$("#radioPickerList");if(!list.hidden){list.hidden=true;return}loadRadioPickerTracks()});
$("#radioPickerList").addEventListener("click",event=>{const btn=event.target.closest("[data-radio-track-id]");if(btn)importRadioTrack(btn.dataset.radioTrackId,btn.dataset.radioTrackTitle)});
$("#uploadArtworkButton").addEventListener("click",uploadArtwork);
$("#deleteArtworkButton").addEventListener("click",deleteArtwork);
$("#artworkFile").addEventListener("change",()=>{const file=$("#artworkFile").files?.[0];uploadUi.artwork.idle(file?uploadReadyLabel(file):"No file selected.")});
$("#versionArtworkFile").addEventListener("change",()=>{const file=$("#versionArtworkFile").files?.[0];uploadUi.versionArtwork.idle(file?uploadReadyLabel(file):"No file selected.")});
$("#uploadVersionArtworkButton").addEventListener("click",uploadVersionArtwork);
$("#deleteVersionArtworkButton").addEventListener("click",deleteVersionArtwork);

$("#versionForm").addEventListener("submit",async event=>{event.preventDefault();try{const data=await api({action:"save_version",songId:$("#versionSongId").value,versionId:$("#versionId").value,versionType:$("#versionType").value,label:$("#versionLabel").value,masteringStatus:$("#masteringStatus").value,audioUrl:$("#audioUrl").value,durationSeconds:$("#durationSeconds").value,targetLufs:$("#targetLufs").value,truePeakDbtp:$("#truePeakDbtp").value,cleanLyrics:$("#cleanLyrics").checked,saleEnabled:$("#saleEnabled").checked,notes:$("#versionNotes").value});elements.versionDialog.close();message(data.message);await loadCatalog(data.songId)}catch(error){message(error.message)}});
$("#reviewButton").addEventListener("click",async()=>{const song=selectedSong();if(!song)return;try{const data=await api({action:"review_song",songId:song.id});message(data.message);await loadCatalog(song.id)}catch(error){message(error.message)}});
$("#runProducerButton").addEventListener("click",runProducer);
$("#producerGrid").addEventListener("click",event=>{const button=event.target.closest("[data-package-status]");if(button)setPackageStatus(button.dataset.packageId,button.dataset.packageStatus)});

loadCatalog();
