INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  genres,
  artwork_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  pitch,
  press_description,
  credits,
  available_versions,
  status
)
VALUES (
  'blessed',
  'Blessed',
  'Owen Anthony',
  '2026-08-26',
  ARRAY['Electronic'],
  '/assets/releases/blessed.jpg',
  'https://distrokid.com/hyperfollow/owenanthony/blessed',
  '/release-kit.html?audience=dj&slug=blessed',
  '/release-kit.html?audience=radio&slug=blessed',
  '/release-kit.html?audience=press&slug=blessed',
  'Blessed is Owen Anthony''s official release destination, connected to one local HALO artwork path and release servicing room.',
  'Released August 26, 2026, Blessed is now published in the HALO catalog with local artwork, HyperFollow access, and campaign routing for DJs, radio, and press.',
  'Owen Anthony — primary artist',
  ARRAY['Official streaming release', 'DJ support request', 'Radio support request', 'Press support request', 'Cover artwork and release details'],
  'published'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  release_date = EXCLUDED.release_date,
  genres = EXCLUDED.genres,
  artwork_url = EXCLUDED.artwork_url,
  official_url = EXCLUDED.official_url,
  dj_url = EXCLUDED.dj_url,
  radio_url = EXCLUDED.radio_url,
  press_url = EXCLUDED.press_url,
  pitch = EXCLUDED.pitch,
  press_description = EXCLUDED.press_description,
  credits = EXCLUDED.credits,
  available_versions = EXCLUDED.available_versions,
  status = EXCLUDED.status,
  updated_at = NOW();
