INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  artwork_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  pitch,
  press_description,
  available_versions,
  status
)
VALUES
  (
    'ghost-to-me',
    'Ghost To Me',
    'Owen Anthony',
    '2026-07-31',
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--09DF4B3E-7039-4B70-A72A00F687EC4AF7--0--2383028--GeminiGeneratedImage2xiyaa2xiyaa2xiy.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=c45f22604913369e2e1087a91597eee3',
    'https://distrokid.com/hyperfollow/owenanthony/ghost-to-me',
    '/release-kit.html?audience=dj&slug=ghost-to-me',
    '/release-kit.html?audience=radio&slug=ghost-to-me',
    '/release-kit.html?audience=press&slug=ghost-to-me',
    'Ghost To Me is an official Owen Anthony release with one verified path to streaming services, video, and HALO campaign rooms.',
    'Ghost To Me was released by Owen Anthony on July 31, 2026. The HALO release room connects the verified HyperFollow destination with listener, DJ, radio, and press paths.',
    ARRAY['Official streaming release', 'Official video', 'Artwork and verified release details', 'DJ, radio, and press enquiries'],
    'published'
  ),
  (
    'beautiful-liar-anna',
    'Beautiful Liar',
    'Halo Music',
    '2026-07-06',
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--DF046703-3686-46C6-97024EFF2D758EE7--0--9237399--GeminiGeneratedImage7mpjnj7mpjnj7mpj.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=b7270efb23e593e514e4f20c07771209',
    'https://distrokid.com/hyperfollow/halomusic1/beautiful-lie-anna',
    '/release-kit.html?audience=dj&slug=beautiful-liar-anna',
    '/release-kit.html?audience=radio&slug=beautiful-liar-anna',
    '/release-kit.html?audience=press&slug=beautiful-liar-anna',
    'Beautiful Liar is an official Halo Music release with a verified destination for listening and campaign support.',
    'Beautiful Liar was released by Halo Music on July 6, 2026. Its HALO release room gives listeners and professional partners a direct route to the verified release.',
    ARRAY['Official streaming release', 'Artwork and verified release details', 'DJ, radio, and press enquiries'],
    'published'
  ),
  (
    'my-decision-dj-halo-mix-special-version',
    'My Decision: DJ Halo Mix (Special Version)',
    'Halo Music',
    '2026-07-04',
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--E563038C-DCC3-41B3-9B1D9860E43E497F--0--1899075--GeminiGeneratedImageamb6hsamb6hsamb6.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=085dc53d6e792ccf29e6f92153ec00cc',
    'https://distrokid.com/hyperfollow/halomusic1/my-decision--dj-halo-mix-special-version',
    '/release-kit.html?audience=dj&slug=my-decision-dj-halo-mix-special-version',
    '/release-kit.html?audience=radio&slug=my-decision-dj-halo-mix-special-version',
    '/release-kit.html?audience=press&slug=my-decision-dj-halo-mix-special-version',
    'My Decision: DJ Halo Mix (Special Version) is an official Halo Music release connected to its verified listening page and HALO campaign rooms.',
    'This special DJ Halo mix of My Decision was released by Halo Music on July 4, 2026, with direct paths for listeners, DJs, radio teams, and press.',
    ARRAY['Official streaming release', 'Special DJ Halo mix', 'Artwork and verified release details', 'DJ, radio, and press enquiries'],
    'published'
  ),
  (
    'beautiful-liar-owen-anthony',
    'Beautiful Liar',
    'Owen Anthony',
    '2026-07-07',
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--95E8398C-2659-4BE5-9FA7FEEEBB0726D9--0--8930009--GeminiGeneratedImagenjo23snjo23snjo2.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=cec4fb143573af812174f7f4a85c87de',
    'https://distrokid.com/hyperfollow/halomusic1/beautiful-lie',
    '/release-kit.html?audience=dj&slug=beautiful-liar-owen-anthony',
    '/release-kit.html?audience=radio&slug=beautiful-liar-owen-anthony',
    '/release-kit.html?audience=press&slug=beautiful-liar-owen-anthony',
    'Beautiful Liar is an official Owen Anthony release with verified streaming and video destinations connected through HALO.',
    'Beautiful Liar was released by Owen Anthony on July 7, 2026. The release room brings its verified HyperFollow page, official video, and professional campaign paths together.',
    ARRAY['Official streaming release', 'Official video', 'Artwork and verified release details', 'DJ, radio, and press enquiries'],
    'published'
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  release_date = EXCLUDED.release_date,
  artwork_url = EXCLUDED.artwork_url,
  official_url = EXCLUDED.official_url,
  dj_url = EXCLUDED.dj_url,
  radio_url = EXCLUDED.radio_url,
  press_url = EXCLUDED.press_url,
  pitch = EXCLUDED.pitch,
  press_description = EXCLUDED.press_description,
  available_versions = EXCLUDED.available_versions,
  status = EXCLUDED.status,
  updated_at = NOW();

UPDATE halo_artist_pages
SET
  tagline = 'Ghost To Me, available now.',
  bio = 'Owen Anthony creates records that connect direct songwriting with the HALO production world. This room brings the latest verified release, official visuals, professional campaign paths, and the wider catalog together under one permanent address.',
  accent_color = '#d5ff52',
  artwork_url = 'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--09DF4B3E-7039-4B70-A72A00F687EC4AF7--0--2383028--GeminiGeneratedImage2xiyaa2xiyaa2xiy.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=c45f22604913369e2e1087a91597eee3',
  release_title = 'Ghost To Me',
  release_date = '2026-07-31',
  release_url = 'https://distrokid.com/hyperfollow/owenanthony/ghost-to-me',
  video_title = 'Ghost To Me (DJ Halo X Remix)',
  video_url = 'https://www.youtube.com/watch?v=yh7qQGvzmdw',
  community_url = '/#clubhouse',
  dj_room_url = '/release-kit.html?audience=dj&slug=ghost-to-me',
  radio_room_url = '/release-kit.html?audience=radio&slug=ghost-to-me',
  press_room_url = '/release-kit.html?audience=press&slug=ghost-to-me',
  booking_url = '/creators/',
  website_url = 'https://open.spotify.com/album/0QHIVfQ1RiDK6kR0DqcPhC',
  status = 'published',
  updated_at = NOW()
WHERE slug = 'owen-anthony';

INSERT INTO halo_artist_pages (
  slug,
  artist_name,
  tagline,
  bio,
  accent_color,
  artwork_url,
  release_title,
  release_date,
  release_url,
  community_url,
  dj_room_url,
  radio_room_url,
  press_room_url,
  booking_url,
  website_url,
  status
)
VALUES (
  'halo-music',
  'Halo Music',
  'Beautiful Liar, available now.',
  'Halo Music is the release identity connecting original records, special mixes, and the wider HALO creative network. This room keeps verified listening links, campaign tools, and the growing catalog together in one place.',
  '#d5ff52',
  'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--DF046703-3686-46C6-97024EFF2D758EE7--0--9237399--GeminiGeneratedImage7mpjnj7mpjnj7mpj.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=b7270efb23e593e514e4f20c07771209',
  'Beautiful Liar',
  '2026-07-06',
  'https://distrokid.com/hyperfollow/halomusic1/beautiful-lie-anna',
  '/#clubhouse',
  '/release-kit.html?audience=dj&slug=beautiful-liar-anna',
  '/release-kit.html?audience=radio&slug=beautiful-liar-anna',
  '/release-kit.html?audience=press&slug=beautiful-liar-anna',
  '/creators/',
  'https://open.spotify.com/album/4KRexkjrzDAak5tT44bzh3',
  'published'
)
ON CONFLICT (slug) DO UPDATE SET
  artist_name = EXCLUDED.artist_name,
  tagline = EXCLUDED.tagline,
  bio = EXCLUDED.bio,
  accent_color = EXCLUDED.accent_color,
  artwork_url = EXCLUDED.artwork_url,
  release_title = EXCLUDED.release_title,
  release_date = EXCLUDED.release_date,
  release_url = EXCLUDED.release_url,
  community_url = EXCLUDED.community_url,
  dj_room_url = EXCLUDED.dj_room_url,
  radio_room_url = EXCLUDED.radio_room_url,
  press_room_url = EXCLUDED.press_room_url,
  booking_url = EXCLUDED.booking_url,
  website_url = EXCLUDED.website_url,
  status = EXCLUDED.status,
  updated_at = NOW();
