CREATE TABLE IF NOT EXISTS halo_artist_economy_profiles (
  artist_slug TEXT PRIMARY KEY REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  currency TEXT NOT NULL DEFAULT 'GBP',
  career_stage TEXT NOT NULL DEFAULT 'first_master',
  monthly_income_target_minor BIGINT NOT NULL DEFAULT 0,
  artist_pay_bps INTEGER NOT NULL DEFAULT 5000,
  next_music_bps INTEGER NOT NULL DEFAULT 2000,
  audience_bps INTEGER NOT NULL DEFAULT 1500,
  business_reserve_bps INTEGER NOT NULL DEFAULT 1000,
  experiment_bps INTEGER NOT NULL DEFAULT 500,
  payment_model TEXT NOT NULL DEFAULT 'undecided',
  payment_status TEXT NOT NULL DEFAULT 'not_connected',
  mission_note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (currency ~ '^[A-Z]{3}$'),
  CHECK (career_stage IN ('first_master', 'first_audience', 'repeatable_releases', 'professional_opportunities', 'sustainable_catalogue')),
  CHECK (monthly_income_target_minor BETWEEN 0 AND 100000000000),
  CHECK (artist_pay_bps BETWEEN 0 AND 10000),
  CHECK (next_music_bps BETWEEN 0 AND 10000),
  CHECK (audience_bps BETWEEN 0 AND 10000),
  CHECK (business_reserve_bps BETWEEN 0 AND 10000),
  CHECK (experiment_bps BETWEEN 0 AND 10000),
  CHECK (artist_pay_bps + next_music_bps + audience_bps + business_reserve_bps + experiment_bps = 10000),
  CHECK (payment_model IN ('undecided', 'artist_seller', 'halo_merchant')),
  CHECK (payment_status IN ('not_connected', 'preparing', 'restricted', 'ready')),
  CHECK (char_length(mission_note) <= 2000)
);

CREATE TABLE IF NOT EXISTS halo_artist_rights_works (
  id TEXT PRIMARY KEY,
  artist_slug TEXT NOT NULL REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  work_type TEXT NOT NULL DEFAULT 'recording',
  linked_release_id TEXT REFERENCES halo_release_campaigns(id) ON DELETE SET NULL,
  isrc TEXT NOT NULL DEFAULT '',
  iswc TEXT NOT NULL DEFAULT '',
  upc TEXT NOT NULL DEFAULT '',
  rights_status TEXT NOT NULL DEFAULT 'incomplete',
  one_stop BOOLEAN NOT NULL DEFAULT FALSE,
  master_owner TEXT NOT NULL DEFAULT '',
  publisher_status TEXT NOT NULL DEFAULT 'unknown',
  restrictions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (char_length(title) BETWEEN 1 AND 180),
  CHECK (work_type IN ('recording', 'composition')),
  CHECK (char_length(isrc) <= 15),
  CHECK (char_length(iswc) <= 20),
  CHECK (char_length(upc) <= 20),
  CHECK (rights_status IN ('incomplete', 'review', 'cleared', 'hold', 'disputed')),
  CHECK (char_length(master_owner) <= 180),
  CHECK (publisher_status IN ('unknown', 'self_published', 'administered', 'publisher_controlled')),
  CHECK (cardinality(restrictions) <= 20),
  CHECK (char_length(notes) <= 4000)
);

CREATE TABLE IF NOT EXISTS halo_artist_rights_participants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  work_id TEXT NOT NULL REFERENCES halo_artist_rights_works(id) ON DELETE CASCADE,
  participant_name TEXT NOT NULL,
  role TEXT NOT NULL,
  share_bps INTEGER NOT NULL DEFAULT 0,
  collection_status TEXT NOT NULL DEFAULT 'unconfirmed',
  society_name TEXT NOT NULL DEFAULT '',
  identifier TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (char_length(participant_name) BETWEEN 1 AND 180),
  CHECK (role IN ('master_owner', 'songwriter', 'publisher', 'producer', 'featured_artist', 'performer', 'manager', 'other')),
  CHECK (share_bps BETWEEN 0 AND 10000),
  CHECK (collection_status IN ('unconfirmed', 'registered', 'collecting', 'hold')),
  CHECK (char_length(society_name) <= 120),
  CHECK (char_length(identifier) <= 120)
);

CREATE TABLE IF NOT EXISTS halo_artist_income_entries (
  id TEXT PRIMARY KEY,
  artist_slug TEXT NOT NULL REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  work_id TEXT REFERENCES halo_artist_rights_works(id) ON DELETE SET NULL,
  source_type TEXT NOT NULL,
  description TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'GBP',
  gross_minor BIGINT NOT NULL DEFAULT 0,
  fees_minor BIGINT NOT NULL DEFAULT 0,
  tax_reserve_minor BIGINT NOT NULL DEFAULT 0,
  obligations_minor BIGINT NOT NULL DEFAULT 0,
  occurred_on DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'expected',
  external_reference TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (source_type IN ('distribution', 'publishing', 'neighbouring_rights', 'direct_sale', 'membership', 'licensing', 'live', 'merchandise', 'service', 'grant', 'other')),
  CHECK (char_length(description) BETWEEN 1 AND 240),
  CHECK (currency ~ '^[A-Z]{3}$'),
  CHECK (gross_minor BETWEEN 0 AND 100000000000),
  CHECK (fees_minor BETWEEN 0 AND gross_minor),
  CHECK (tax_reserve_minor BETWEEN 0 AND gross_minor),
  CHECK (obligations_minor BETWEEN 0 AND gross_minor),
  CHECK (fees_minor + tax_reserve_minor + obligations_minor <= gross_minor),
  CHECK (status IN ('expected', 'received', 'overdue', 'disputed', 'reconciled')),
  CHECK (char_length(external_reference) <= 180),
  CHECK (char_length(notes) <= 4000)
);

CREATE TABLE IF NOT EXISTS halo_artist_campaign_investments (
  id TEXT PRIMARY KEY,
  artist_slug TEXT NOT NULL REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  stage TEXT NOT NULL DEFAULT 'readiness',
  objective TEXT NOT NULL DEFAULT 'retained_fan',
  currency TEXT NOT NULL DEFAULT 'GBP',
  budget_minor BIGINT NOT NULL DEFAULT 0,
  spent_minor BIGINT NOT NULL DEFAULT 0,
  meaningful_actions INTEGER NOT NULL DEFAULT 0,
  stop_loss_minor BIGINT NOT NULL DEFAULT 0,
  decision TEXT NOT NULL DEFAULT 'prepare',
  learning TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (char_length(title) BETWEEN 1 AND 180),
  CHECK (stage IN ('readiness', 'test', 'scale', 'closed')),
  CHECK (objective IN ('completed_listen', 'retained_fan', 'direct_sale', 'event_registration', 'licensing_lead', 'other')),
  CHECK (currency ~ '^[A-Z]{3}$'),
  CHECK (budget_minor BETWEEN 0 AND 100000000000),
  CHECK (spent_minor BETWEEN 0 AND budget_minor),
  CHECK (meaningful_actions BETWEEN 0 AND 100000000),
  CHECK (stop_loss_minor BETWEEN 0 AND budget_minor),
  CHECK (decision IN ('prepare', 'test', 'scale', 'stop', 'complete')),
  CHECK (char_length(learning) <= 4000)
);

CREATE TABLE IF NOT EXISTS halo_artist_licensing_opportunities (
  id TEXT PRIMARY KEY,
  artist_slug TEXT NOT NULL REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  work_id TEXT REFERENCES halo_artist_rights_works(id) ON DELETE SET NULL,
  opportunity_name TEXT NOT NULL,
  buyer_name TEXT NOT NULL DEFAULT '',
  media_type TEXT NOT NULL DEFAULT 'other',
  territory TEXT NOT NULL DEFAULT 'worldwide',
  currency TEXT NOT NULL DEFAULT 'GBP',
  quoted_fee_minor BIGINT NOT NULL DEFAULT 0,
  commission_bps INTEGER NOT NULL DEFAULT 0,
  stage TEXT NOT NULL DEFAULT 'brief',
  rights_check TEXT NOT NULL DEFAULT 'required',
  decision_due_at TIMESTAMPTZ,
  restrictions TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (char_length(opportunity_name) BETWEEN 1 AND 200),
  CHECK (char_length(buyer_name) <= 180),
  CHECK (media_type IN ('film', 'television', 'advertising', 'game', 'trailer', 'creator', 'documentary', 'other')),
  CHECK (char_length(territory) <= 120),
  CHECK (currency ~ '^[A-Z]{3}$'),
  CHECK (quoted_fee_minor BETWEEN 0 AND 100000000000),
  CHECK (commission_bps BETWEEN 0 AND 5000),
  CHECK (stage IN ('brief', 'matched', 'artist_approval', 'pitched', 'negotiating', 'contracted', 'delivered', 'paid', 'declined')),
  CHECK (rights_check IN ('required', 'reviewing', 'clear', 'hold')),
  CHECK (char_length(restrictions) <= 2000),
  CHECK (char_length(notes) <= 4000)
);

CREATE TABLE IF NOT EXISTS halo_artist_live_engagements (
  id TEXT PRIMARY KEY,
  artist_slug TEXT NOT NULL REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  owner_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  venue_name TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  performance_at TIMESTAMPTZ,
  currency TEXT NOT NULL DEFAULT 'GBP',
  guaranteed_fee_minor BIGINT NOT NULL DEFAULT 0,
  ticket_share_minor BIGINT NOT NULL DEFAULT 0,
  merchandise_minor BIGINT NOT NULL DEFAULT 0,
  costs_minor BIGINT NOT NULL DEFAULT 0,
  tickets_sold INTEGER NOT NULL DEFAULT 0,
  fans_captured INTEGER NOT NULL DEFAULT 0,
  settlement_status TEXT NOT NULL DEFAULT 'planning',
  setlist_reported BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (char_length(title) BETWEEN 1 AND 180),
  CHECK (char_length(venue_name) <= 180),
  CHECK (char_length(city) <= 120),
  CHECK (currency ~ '^[A-Z]{3}$'),
  CHECK (guaranteed_fee_minor BETWEEN 0 AND 100000000000),
  CHECK (ticket_share_minor BETWEEN 0 AND 100000000000),
  CHECK (merchandise_minor BETWEEN 0 AND 100000000000),
  CHECK (costs_minor BETWEEN 0 AND 100000000000),
  CHECK (tickets_sold BETWEEN 0 AND 10000000),
  CHECK (fans_captured BETWEEN 0 AND 10000000),
  CHECK (settlement_status IN ('planning', 'confirmed', 'performed', 'settling', 'paid', 'cancelled')),
  CHECK (char_length(notes) <= 4000)
);

CREATE TABLE IF NOT EXISTS halo_artist_conscience_reviews (
  id TEXT PRIMARY KEY,
  artist_slug TEXT REFERENCES halo_artist_pages(slug) ON DELETE CASCADE,
  created_by_member_id TEXT NOT NULL REFERENCES halo_memberships(member_id) ON DELETE CASCADE,
  proposal_type TEXT NOT NULL,
  title TEXT NOT NULL,
  artist_benefit TEXT NOT NULL,
  artist_risk TEXT NOT NULL DEFAULT '',
  ownership_effect TEXT NOT NULL DEFAULT 'neutral',
  income_effect TEXT NOT NULL DEFAULT 'unknown',
  reversibility TEXT NOT NULL DEFAULT 'reversible',
  decision TEXT NOT NULL DEFAULT 'review',
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  conditions TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (id ~ '^[0-9a-f-]{36}$'),
  CHECK (proposal_type IN ('product', 'fee', 'algorithm', 'partnership', 'campaign', 'licensing', 'policy', 'other')),
  CHECK (char_length(title) BETWEEN 1 AND 200),
  CHECK (char_length(artist_benefit) BETWEEN 1 AND 4000),
  CHECK (char_length(artist_risk) <= 4000),
  CHECK (ownership_effect IN ('strengthens', 'neutral', 'weakens')),
  CHECK (income_effect IN ('improves', 'neutral', 'unknown', 'harms')),
  CHECK (reversibility IN ('reversible', 'difficult', 'irreversible')),
  CHECK (decision IN ('review', 'approve', 'revise', 'reject')),
  CHECK (char_length(conditions) <= 4000)
);

CREATE INDEX IF NOT EXISTS halo_artist_economy_owner_idx
  ON halo_artist_economy_profiles(owner_member_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_rights_artist_idx
  ON halo_artist_rights_works(artist_slug, updated_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_rights_participants_work_idx
  ON halo_artist_rights_participants(work_id, role, id);
CREATE INDEX IF NOT EXISTS halo_artist_income_artist_idx
  ON halo_artist_income_entries(artist_slug, occurred_on DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_campaigns_artist_idx
  ON halo_artist_campaign_investments(artist_slug, updated_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_licensing_artist_idx
  ON halo_artist_licensing_opportunities(artist_slug, updated_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_live_artist_idx
  ON halo_artist_live_engagements(artist_slug, performance_at DESC NULLS LAST, updated_at DESC);
CREATE INDEX IF NOT EXISTS halo_artist_conscience_decision_idx
  ON halo_artist_conscience_reviews(decision, updated_at DESC);
