INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  genres,
  artwork_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  pitch,
  press_description,
  credits,
  available_versions,
  status
)
VALUES (
  'ill-do-it-all-again',
  'I''ll Do It All Again',
  'Owen Anthony',
  NULL,
  ARRAY['Hip-Hop', 'Rap'],
  '',
  'https://distrokid.com/hyperfollow/owenanthony/ill-do-it-all-again',
  '/release-kit.html?audience=dj&slug=ill-do-it-all-again',
  '/release-kit.html?audience=radio&slug=ill-do-it-all-again',
  '/release-kit.html?audience=press&slug=ill-do-it-all-again',
  'I''ll Do It All Again is Owen Anthony''s official release, available now on all major streaming platforms.',
  'I''ll Do It All Again is an official Owen Anthony release distributed through DistroKid and available on all major streaming platforms.',
  'Owen Anthony — primary artist',
  ARRAY['Official release', 'DJ support request', 'Radio support request', 'Release details'],
  'published'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  genres = EXCLUDED.genres,
  official_url = EXCLUDED.official_url,
  dj_url = EXCLUDED.dj_url,
  radio_url = EXCLUDED.radio_url,
  press_url = EXCLUDED.press_url,
  pitch = EXCLUDED.pitch,
  press_description = EXCLUDED.press_description,
  credits = EXCLUDED.credits,
  available_versions = EXCLUDED.available_versions,
  status = EXCLUDED.status,
  updated_at = NOW();
