INSERT INTO halo_artist_pages (
  slug,
  artist_name,
  tagline,
  bio,
  accent_color,
  artwork_url,
  release_title,
  release_date,
  release_url,
  video_title,
  video_url,
  community_url,
  dj_room_url,
  radio_room_url,
  press_room_url,
  booking_url,
  website_url,
  status
)
VALUES (
  'dj-halo-x-remix',
  'DJ Halo X Remix',
  'Ghost To Me (Special Version Extended Remix), available now.',
  'DJ Halo X Remix connects extended remixes, official visuals, streaming destinations, and HALO campaign support in one permanent artist room.',
  '#d5ff52',
  'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--DCA3D3C3-09E9-4832-9C9F5BC8294FBC7F--0--2510097--GeminiGeneratedImagepms7wmpms7wmpms7.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=8f7031dbd996d98a16fc29fc17ce380b',
  'Ghost To Me By Owen Anthony Remixed By DJ Halo X (Special Version Extended Remix)',
  '2026-07-28',
  'https://distrokid.com/hyperfollow/djhaloxremix/ghost-to-me-by-owen-anthony-remixed-by-dj-halo-x-special-version-extended-remix-?ref=release',
  'Ghost To Me (DJ Halo X Remix)',
  'https://www.youtube.com/watch?v=yh7qQGvzmdw',
  '/#clubhouse',
  '/release-kit.html?audience=dj&slug=ghost-to-me-dj-halo-x-extended-remix',
  '/release-kit.html?audience=radio&slug=ghost-to-me-dj-halo-x-extended-remix',
  '/release-kit.html?audience=press&slug=ghost-to-me-dj-halo-x-extended-remix',
  '/creators/',
  'https://open.spotify.com/album/0le9iHzYxY3YWM4T8E7CDg',
  'published'
)
ON CONFLICT (slug) DO UPDATE SET
  artist_name = EXCLUDED.artist_name,
  tagline = EXCLUDED.tagline,
  bio = EXCLUDED.bio,
  accent_color = EXCLUDED.accent_color,
  artwork_url = EXCLUDED.artwork_url,
  release_title = EXCLUDED.release_title,
  release_date = EXCLUDED.release_date,
  release_url = EXCLUDED.release_url,
  video_title = EXCLUDED.video_title,
  video_url = EXCLUDED.video_url,
  community_url = EXCLUDED.community_url,
  dj_room_url = EXCLUDED.dj_room_url,
  radio_room_url = EXCLUDED.radio_room_url,
  press_room_url = EXCLUDED.press_room_url,
  booking_url = EXCLUDED.booking_url,
  website_url = EXCLUDED.website_url,
  status = EXCLUDED.status,
  updated_at = NOW();

INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  genres,
  artwork_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  pitch,
  press_description,
  credits,
  available_versions,
  status,
  artist_slug,
  release_stage,
  visibility
)
VALUES
  (
    'what-ive-learned',
    'What I''ve Learned',
    'Owen Anthony',
    '2026-07-10',
    ARRAY[]::TEXT[],
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--E2E1D346-84B4-47CE-B39682A80A3F4097--0--1865782--GeminiGeneratedImagel7btuvl7btuvl7bt.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=08acd00460bd034d9648bb39e90b42a7',
    'https://distrokid.com/hyperfollow/owenanthony/what-ive-learned?ref=release',
    '/release-kit.html?audience=dj&slug=what-ive-learned',
    '/release-kit.html?audience=radio&slug=what-ive-learned',
    '/release-kit.html?audience=press&slug=what-ive-learned',
    'What I''ve Learned connects Owen Anthony''s verified streaming release and official visual with permanent fan and professional campaign paths.',
    'Released July 10, 2026, What I''ve Learned is permanently connected to verified streaming destinations, official artwork, video, and HALO support rooms.',
    'Owen Anthony — primary artist',
    ARRAY['Official HyperFollow and streaming destinations', 'Spotify and Apple Music release links', 'Official video', 'Verified cover artwork and release details', 'DJ, radio, and press campaign rooms'],
    'published',
    'owen-anthony',
    'released',
    'public'
  ),
  (
    'ghost-to-me-dj-halo-x-extended-remix',
    'Ghost To Me By Owen Anthony Remixed By DJ Halo X (Special Version Extended Remix)',
    'DJ Halo X Remix',
    '2026-07-28',
    ARRAY[]::TEXT[],
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--DCA3D3C3-09E9-4832-9C9F5BC8294FBC7F--0--2510097--GeminiGeneratedImagepms7wmpms7wmpms7.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=8f7031dbd996d98a16fc29fc17ce380b',
    'https://distrokid.com/hyperfollow/djhaloxremix/ghost-to-me-by-owen-anthony-remixed-by-dj-halo-x-special-version-extended-remix-?ref=release',
    '/release-kit.html?audience=dj&slug=ghost-to-me-dj-halo-x-extended-remix',
    '/release-kit.html?audience=radio&slug=ghost-to-me-dj-halo-x-extended-remix',
    '/release-kit.html?audience=press&slug=ghost-to-me-dj-halo-x-extended-remix',
    'The special extended remix of Ghost To Me connects the verified release, official visual, Halo TV selection, and professional support paths.',
    'Released July 28, 2026, this extended DJ Halo X remix of Owen Anthony''s Ghost To Me has a permanent release room for listeners, selectors, radio teams, and press.',
    'Owen Anthony — original artist; DJ Halo X — remix',
    ARRAY['Special version extended remix', 'Official HyperFollow and streaming destinations', 'Spotify and Apple Music release links', 'Official video and permanent Halo TV selection', 'Spotify radio playlist link', 'Verified cover artwork and release details', 'DJ, radio, and press campaign rooms'],
    'published',
    'dj-halo-x-remix',
    'released',
    'public'
  ),
  (
    'hit-that-beat-extended-mix',
    'Hit That Beat (Extended Mix)',
    'Owen Anthony',
    '2026-08-02',
    ARRAY[]::TEXT[],
    'https://distrokid.imgix.net/http%3A%2F%2Fgather.fandalism.com%2F13116989--FF9431F8-1158-4F97-8E76767EDE8DF7B2--0--7819053--GeminiGeneratedImagelgfdw9lgfdw9lgfd.png?fm=jpg&mark-y=568&mark-x=620&mark-w=180&q=75&w=800&mark=http%3A%2F%2Fgather.fandalism.com%2Fdistrokid-sticker-sm.png&s=cfaf0d40ed50e5188dada5598da81482',
    'https://distrokid.com/hyperfollow/owenanthony/hit-that-beat-extended-mix?ref=release',
    '/release-kit.html?audience=dj&slug=hit-that-beat-extended-mix',
    '/release-kit.html?audience=radio&slug=hit-that-beat-extended-mix',
    '/release-kit.html?audience=press&slug=hit-that-beat-extended-mix',
    'Hit That Beat (Extended Mix) is permanently connected to its verified streaming release and HALO campaign support for listeners, DJs, radio teams, and press.',
    'Released August 2, 2026, Hit That Beat (Extended Mix) has a permanent campaign room with verified artwork, streaming destinations, and professional support paths.',
    'Owen Anthony — primary artist',
    ARRAY['Extended mix', 'Official HyperFollow and streaming destinations', 'Spotify and Apple Music release links', 'Verified cover artwork and release details', 'DJ, radio, and press campaign rooms'],
    'published',
    'owen-anthony',
    'released',
    'public'
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  release_date = EXCLUDED.release_date,
  genres = EXCLUDED.genres,
  artwork_url = EXCLUDED.artwork_url,
  official_url = EXCLUDED.official_url,
  dj_url = EXCLUDED.dj_url,
  radio_url = EXCLUDED.radio_url,
  press_url = EXCLUDED.press_url,
  pitch = EXCLUDED.pitch,
  press_description = EXCLUDED.press_description,
  credits = EXCLUDED.credits,
  available_versions = EXCLUDED.available_versions,
  status = EXCLUDED.status,
  artist_slug = EXCLUDED.artist_slug,
  release_stage = EXCLUDED.release_stage,
  visibility = EXCLUDED.visibility,
  updated_at = NOW();

UPDATE halo_artist_pages
SET
  current_release_id = 'ghost-to-me-dj-halo-x-extended-remix',
  updated_at = NOW()
WHERE slug = 'dj-halo-x-remix';
