ALTER TABLE community_profiles
  ADD COLUMN IF NOT EXISTS persona_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS persona_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS persona_bio TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS visibility_level TEXT NOT NULL DEFAULT 'community';
