-- Normalize the requested HALO music releases to the current catalog contract so
-- they always appear cleanly in /music on a fresh deploy.
INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  genres,
  artwork_url,
  imported_artwork_url,
  artwork_override_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  purchase_url,
  pitch,
  press_description,
  credits,
  available_versions,
  is_clean_version,
  is_chart_eligible,
  status
)
VALUES
  (
    'cognitive-erasure',
    'Cognitive Erasure',
    'Owen Anthony',
    NULL,
    ARRAY['Hip-Hop', 'Rap'],
    '/assets/halo-app-icon-512.png',
    '',
    '',
    'https://distrokid.com/hyperfollow/owenanthony/cognitive-erasure?ref=release',
    '/release-kit.html?audience=dj&slug=cognitive-erasure',
    '/release-kit.html?audience=radio&slug=cognitive-erasure',
    '/release-kit.html?audience=press&slug=cognitive-erasure',
    'https://distrokid.com/hyperfollow/owenanthony/cognitive-erasure?ref=release',
    'Cognitive Erasure is Owen Anthony''s official release, available now on all major streaming platforms.',
    'Cognitive Erasure is an official Owen Anthony release distributed through DistroKid and available on all major streaming platforms.',
    'Owen Anthony — primary artist',
    ARRAY['Official streaming release'],
    TRUE,
    TRUE,
    'published'
  ),
  (
    'blessed',
    'Blessed',
    'Owen Anthony',
    NULL,
    ARRAY['Hip-Hop', 'Rap'],
    '/assets/halo-app-icon-512.png',
    '',
    '',
    'https://distrokid.com/hyperfollow/owenanthony/blessed?ref=release',
    '/release-kit.html?audience=dj&slug=blessed',
    '/release-kit.html?audience=radio&slug=blessed',
    '/release-kit.html?audience=press&slug=blessed',
    'https://distrokid.com/hyperfollow/owenanthony/blessed?ref=release',
    'Blessed is Owen Anthony''s official release, available now on all major streaming platforms.',
    'Blessed is an official Owen Anthony release distributed through DistroKid and available on all major streaming platforms.',
    'Owen Anthony — primary artist',
    ARRAY['Official streaming release'],
    TRUE,
    TRUE,
    'published'
  ),
  (
    'my-sensitivity-like-a-crown',
    'My Sensitivity Like a Crown',
    'Owen Anthony',
    NULL,
    ARRAY['Hip-Hop', 'Rap', 'R&B / Soul'],
    '/assets/releases/my-sensitivity-like-a-crown.jpg',
    '',
    '',
    'https://distrokid.com/hyperfollow/owenanthony/my-sensitivity-like-a-crown',
    '/release-kit.html?audience=dj&slug=my-sensitivity-like-a-crown',
    '/release-kit.html?audience=radio&slug=my-sensitivity-like-a-crown',
    '/release-kit.html?audience=press&slug=my-sensitivity-like-a-crown',
    'https://distrokid.com/hyperfollow/owenanthony/my-sensitivity-like-a-crown',
    'My Sensitivity Like a Crown is Owen Anthony''s official release, available now on all major streaming platforms.',
    'My Sensitivity Like a Crown is an official Owen Anthony release distributed through DistroKid and available on all major streaming platforms.',
    'Owen Anthony — primary artist',
    ARRAY['Official streaming release', 'Radio edit', 'Clean version', 'Instrumental'],
    TRUE,
    TRUE,
    'published'
  ),
  (
    'when-the-world-goes-dark',
    'When The World Goes Dark',
    'Owen Anthony',
    '2026-08-20',
    ARRAY['Electronic', 'Cinematic'],
    '/assets/releases/when-the-world-goes-dark.jpg',
    '',
    '',
    'https://distrokid.com/hyperfollow/owenanthony/when-the-world-goes-dark?ref=release',
    '/release-kit.html?audience=dj&slug=when-the-world-goes-dark',
    '/release-kit.html?audience=radio&slug=when-the-world-goes-dark',
    '/release-kit.html?audience=press&slug=when-the-world-goes-dark',
    'https://distrokid.com/hyperfollow/owenanthony/when-the-world-goes-dark?ref=release',
    'A cinematic electronic transmission about protecting the last human signal when certainty, connection, and light disappear.',
    'Released August 20, 2026, When The World Goes Dark expands into The Last Light Network: a participatory digital ritual where every listener leaves one persistent pulse before entering the record.',
    'Owen Anthony — primary artist, songwriter, and producer',
    ARRAY['Official streaming release', 'The Last Light Network fan experience', 'Persistent listener pulse map', 'DJ campaign room', 'Radio campaign room', 'Press campaign room', 'Official cover artwork and release details'],
    TRUE,
    TRUE,
    'published'
  )
ON CONFLICT (id) DO UPDATE SET
  title                = EXCLUDED.title,
  artist               = EXCLUDED.artist,
  release_date         = EXCLUDED.release_date,
  genres               = EXCLUDED.genres,
  artwork_url          = EXCLUDED.artwork_url,
  imported_artwork_url = COALESCE(NULLIF(EXCLUDED.imported_artwork_url, ''), halo_release_campaigns.imported_artwork_url),
  artwork_override_url = COALESCE(NULLIF(EXCLUDED.artwork_override_url, ''), halo_release_campaigns.artwork_override_url),
  official_url         = EXCLUDED.official_url,
  dj_url               = EXCLUDED.dj_url,
  radio_url            = EXCLUDED.radio_url,
  press_url            = EXCLUDED.press_url,
  purchase_url         = EXCLUDED.purchase_url,
  pitch                = EXCLUDED.pitch,
  press_description    = EXCLUDED.press_description,
  credits              = EXCLUDED.credits,
  available_versions   = EXCLUDED.available_versions,
  is_clean_version     = EXCLUDED.is_clean_version,
  is_chart_eligible    = EXCLUDED.is_chart_eligible,
  status               = EXCLUDED.status,
  updated_at           = NOW();
