INSERT INTO halo_release_campaigns (
  id,
  title,
  artist,
  release_date,
  duration,
  genres,
  artwork_url,
  official_url,
  dj_url,
  radio_url,
  press_url,
  pitch,
  press_description,
  credits,
  available_versions,
  status
)
VALUES (
  'salty',
  'Salty',
  'Owen Anthony',
  '2026-08-17',
  '4:48',
  ARRAY['Electronic', 'Afrobeat'],
  '/assets/releases/salty.jpg',
  'https://distrokid.com/hyperfollow/owenanthony/salty?ref=release',
  '/release-kit.html?audience=dj&slug=salty',
  '/release-kit.html?audience=radio&slug=salty',
  '/release-kit.html?audience=press&slug=salty',
  'Salty is Owen Anthony''s newest electronic and Afrobeat release, connected to one permanent listening and campaign room.',
  'Released August 17, 2026, Salty brings its official listening destination, artwork, and professional support paths into the HALO catalog.',
  'Owen Anthony — primary artist',
  ARRAY['Official release', 'DJ support request', 'Radio support request', 'Cover artwork and release details'],
  'published'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  artist = EXCLUDED.artist,
  release_date = EXCLUDED.release_date,
  duration = EXCLUDED.duration,
  genres = EXCLUDED.genres,
  artwork_url = EXCLUDED.artwork_url,
  official_url = EXCLUDED.official_url,
  dj_url = EXCLUDED.dj_url,
  radio_url = EXCLUDED.radio_url,
  press_url = EXCLUDED.press_url,
  pitch = EXCLUDED.pitch,
  press_description = EXCLUDED.press_description,
  credits = EXCLUDED.credits,
  available_versions = EXCLUDED.available_versions,
  status = EXCLUDED.status,
  updated_at = NOW();
